#' Simulated Continuous Glucose Monitoring (CGM) Dataset
#'
#' `raw_cgm` contains fully synthetic continuous glucose monitoring (CGM)
#' measurements generated at a 5‑minute sampling rate over a 14‑day period
#' for two simulated participants (`P01` and `P02`).
#' The dataset is designed to reflect realistic day‑to‑day variability in
#' glucose‑like numerical signals, including higher‑value excursions,
#' lower‑value dips, circadian changes, meal‑related peaks, overnight
#' reductions, and stochastic variability.
#'
#' @details
#'
#' \strong{Participants}
#'
#' \itemize{
#'   \item \code{"P01"} — CGM begins at \code{"2026‑01‑01 07:17:00"} (UTC)
#'   \item \code{"P02"} — CGM begins at \code{"2026‑01‑02 15:52:00"} (UTC)
#' }
#'
#' Each participant is simulated for exactly **14 days** with a **5‑minute**
#' sampling interval (288 points per day before missingness).
#'
#'
#' \strong{Generation script}
#'
#' This dataset is produced reproducibly using:
#'
#' \preformatted{
#'   data-raw/simulate_raw_cgm.R
#' }
#'
#'
#' @format A tibble with three columns:
#' \describe{
#'   \item{id}{Character ID for the participant (\code{"P01"} or \code{"P02"}).}
#'
#'   \item{cgm_timestamp}{POSIXct timestamp in UTC at nominal 5‑minute cadence,
#'                        with implicit gaps due to simulated missingness.}
#'
#'   \item{glucose}{Numeric synthetic glucose‑like value in mmol/L.}
#' }
#'
#'
#' @examples
#' data(raw_cgm, package = "hypometrics")
#'
#' # Inspect structure
#' dplyr::glimpse(raw_cgm)
#'
#' # Example: plot first 48 hours of P01
#' raw_cgm %>%
#'   dplyr::filter(id == "P01") %>%
#'   dplyr::arrange(cgm_timestamp) %>%
#'   dplyr::slice(1:600) %>%
#'   with(plot(cgm_timestamp, glucose, type = "l"))
"raw_cgm"

#' Simulated interpolated CGM Dataset
#'
#' `cgm` is a derived dataset created from [`raw_cgm`], where glucose values are **linearly
#' interpolated** for **short gaps** while **longer gaps remain missing**.
#'
#' @details
#'
#' The dataset is generated by
#' \code{hypometrics::cgmInterpolate()} as follows:
#'
#' \itemize{
#'   \item \strong{Input:} [`raw_cgm`].
#'   \item \strong{Explicit gaps:} Gaps are first made explicit when
#'         transforming to the target grid (5‑minute).
#'   \item \strong{Interpolation:} Linear interpolation is applied to gaps
#'         whose duration is \emph{strictly less than} \strong{30 minutes}
#'         (\code{MaxGap = 1800} seconds).
#'   \item \strong{Long gaps:} Gaps \strong{≥ 30 minutes} are \emph{not}
#'         interpolated; glucose remains \code{NA}.
#'   \item \strong{Granularity:} The target resolution is \strong{5 minutes}
#'         (\code{Granularity = 300} seconds).
#' }
#'
#' This procedure retains the two synthetic participants from [`raw_cgm`]
#' (IDs \code{"P01"}, \code{"P02"}), their distinct profiles, and their
#' hypoglycaemia patterns, while providing a regularised 5‑minute time series
#' that is convenient for summaries, visualisation, and episode detection.
#'
#' @format A tibble with the following columns:
#' \describe{
#'   \item{id}{Character. Participant ID (\code{"P01"}, \code{"P02"}).}
#'   \item{cgm_timestamp}{POSIXct. CGM timestamp in UTC at \strong{1‑minute} intervals.}
#'   \item{glucose}{Numeric. Glucose concentration in mmol/L. Observed values
#'     where available; \code{NA} in gaps \strong{≥ 30 minutes}; linearly
#'     interpolated in gaps \strong{< 30 minutes}.}
#' }
#'
#' @source Generated by \code{data-raw/derive_cgm_from_raw.R} using:
#' \preformatted{
#' cgm <- hypometrics::cgmInterpolate(
#'   raw_cgm,
#'   Interpolate = TRUE,
#'   MinGap      = 600,   # only act when gaps are at least 10 minutes
#'   Granularity = 300,    # 5-minute target grid  <-- IMPORTANT
#'   MaxGap      = 1800   # interpolate gaps < 30 minutes; leave >= 30 as NA
#' )
#' }
#'
#' @examples
#' data(cgm, package = "hypometrics")
#'
#' # Structure
#' dplyr::glimpse(cgm)
"cgm"


#' Simulated Fitbit Sleep Dataset
#'
#' `raw_sleep` provides a fully simulated set of sleep data for two
#' synthetic participants (`P01` and `P02`). Each record represents a single
#' night of sleep, with realistic bedtimes and wake times, unique nightly
#' identifiers, and occasional missing nights to mirror imperfect real‑world
#' device collection.
#'
#' The dataset is intended solely for
#' demonstration, examples, and testing within the `hypometrics` package.
#'
#'
#' @details
#'
#' \strong{Participants and date coverage}
#'
#' \itemize{
#'   \item \code{"P01"} — first night: \code{"2026‑01‑01"}
#'   \item \code{"P02"} — first night: \code{"2026‑01‑02"}
#' }
#'
#' Each participant is simulated for **13 consecutive nights**, after which
#' **2–3 randomly selected nights are removed completely** to mimic missing
#' Fitbit‑style nights of sleep.
#'
#' \strong{Generation script}
#'
#' The dataset is generated reproducibly from:
#'
#' \preformatted{
#' data-raw/simulate_raw_sleep.R
#' }
#'
#'
#' @format A tibble with the following columns:
#' \describe{
#'
#'   \item{id}{Character participant ID: \code{"P01"} or \code{"P02"}.}
#'
#'   \item{logId}{Unique 10‑digit numeric identifier for the sleep log.}
#'
#'   \item{dateOfSleep}{Character date (YYYY‑MM‑DD) representing the date of sleep.}
#'
#'   \item{startTime}{POSIXct datetime marking the start of the sleep period.}
#'
#'   \item{endTime}{POSIXct datetime marking the end of the sleep period.}
#'
#' }
#'
#'
#' @examples
#' data(raw_sleep, package = "hypometrics")
#'
#' # View structure
#' dplyr::glimpse(raw_sleep)
#'
#' # Sleep duration for the first few nights
#' raw_sleep %>%
#'   dplyr::mutate(duration_hours =
#'       as.numeric(difftime(endTime, startTime, units = "hours"))) %>%
#'   head()
#'
"raw_sleep"


#' Simulated Minute‑Level Step Count Data
#'
#' `raw_step` contains **synthetic Fitbit‑style step count data** for two
#' simulated participants (`P01` and `P02`). The dataset spans **two weeks**
#' at **1‑minute resolution**. It includes **exercise sessions**,
#' **sleep‑related inactivity**, and **Fitbit‑like missingness patterns**,
#' providing a realistic structure for testing algorithms that process wearable activity data.
#'
#' @details
#'
#' \strong{Participants}
#'
#' \itemize{
#'   \item \code{"P01"} — starts at \code{"2026‑01‑01 07:17:00"} (UTC)
#'   \item \code{"P02"} — starts at \code{"2026‑01‑02 15:52:00"} (UTC)
#' }
#'
#' Each participant has exactly **14 days** of simulated minute‑level data.
#'
#'
#' \strong{Activity patterns}
#'
#' \itemize{
#'   \item \strong{Daytime activity:} mild random movement with realistic variability.
#'   \item \strong{Sleep inactivity:} step counts drop to near‑zero between 23:00–06:00.
#'   \item \strong{Exercise sessions:} intermittent bouts with ramp‑up,
#'     sustained high counts, and gradual cooldown.
#'   \item \strong{Noise:} stochastic variation representing device and behavioural variation.
#' }
#'
#'
#' \strong{Missingness model (Fitbit‑like)}
#'
#' Step counts include NA values introduced using:
#'
#' \itemize{
#'   \item \emph{tiny micro‑gaps} (1–2 minute sensor losses),
#'   \item \emph{longer dropouts} (10–60 minutes).
#' }
#'
#' These patterns mimic real‑world wrist‑worn accelerometer behaviour during
#' motion artifacts, device removal, or Bluetooth disconnection.
#'
#'
#' \strong{Generation script}
#'
#' This dataset is produced reproducibly by the script:
#'
#' \preformatted{
#'   data-raw/simulate_raw_step.R
#' }
#'
#'
#' @format A tibble with three columns:
#' \describe{
#'   \item{id}{Character participant ID (\code{"P01"}, \code{"P02"}).}
#'   \item{step_timestamp}{POSIXct timestamp in UTC, at 1‑minute resolution.}
#'   \item{count}{Whole‑number step count per minute.}
#' }
#'
#'
#' @examples
#' data(raw_step, package = "hypometrics")
#'
#' # Structure
#' dplyr::glimpse(raw_step)
#'
#' # First few rows for P01
#' dplyr::filter(raw_step, id == "P01") %>% head()
#'
#' # Missingness percentage per participant
#' raw_step %>%
#'   dplyr::group_by(id) %>%
#'   dplyr::summarise(
#'     pct_missing = mean(is.na(count)) * 100
#'   )
"raw_step"

#' Simulated Fitbit‑Style Heart Rate Data
#'
#' `raw_hr` contains *synthetic Fitbit‑style heart rate (HR) data* for two
#' simulated participants (`P01` and `P02`). The dataset spans **two weeks**
#' at **1‑minute resolution**, with **realistic physiological patterns**,
#' **exercise sessions**, **sleep‑related HR depressions**, and
#' **Fitbit‑like missingness** (periodic NA values).
#'
#' This dataset is designed for demonstration and testing of HR‑related
#' processing and visualisation tools within the `hypometrics` package.
#'
#' @details
#' The dataset includes:
#'
#' \strong{Participants}
#' \itemize{
#'   \item \code{"P01"} — HR start: \code{"2026‑01‑01 07:17:00"} (UTC)
#'   \item \code{"P02"} — HR start: \code{"2026‑01‑02 15:52:00"} (UTC)
#' }
#'
#' \strong{Simulation features}
#' \itemize{
#'   \item 1‑minute HR sampling for 14 days per participant
#'   \item Circadian rhythm (afternoon HR peak, overnight depression)
#'   \item Sleep HR lowering (smaller noise, lower baseline)
#'   \item Stochastic noise resembling optical HR sensors
#'   \item Exercise bouts with HR rise → plateau → recovery
#'   \item Fitbit‑style missingness:
#'         1–2 minute random gaps, occasional long dropouts with NA heart rate
#'   \item HR values are rounded to whole‑number bpm
#' }
#'
#' \strong{Relation to CGM data}
#'
#' The HR timeline is aligned with the simulated CGM dataset [`raw_cgm`]:
#' for each participant, HR starts exactly when CGM monitoring begins and
#' continues for the same two‑week duration.
#'
#' \strong{Generation script}
#'
#' The data are reproducibly generated using:
#'
#' \preformatted{
#'   data-raw/simulate_raw_hr.R
#' }
#'
#' @format A tibble with three columns:
#' \describe{
#'   \item{id}{Character participant ID ("P01", "P02").}
#'   \item{hr_timestamp}{POSIXct timestamp at 1‑minute resolution (UTC).}
#'   \item{heart_rate}{Heart rate in beats per minute (integer).}
#' }
#'
#' @examples
#' data(raw_hr, package = "hypometrics")
#'
#' # Inspect structure
#' dplyr::glimpse(raw_hr)
#'
#' # Check first few HR values for P01
#' dplyr::filter(raw_hr, id == "P01") %>% head()
#'
#' # Distribution of HR
#' hist(raw_hr$heart_rate, breaks = 40, main = "Simulated HR Distribution")
#'
#' # Missingness rate per participant
#' raw_hr %>%
#'   dplyr::group_by(id) %>%
#'   dplyr::summarise(
#'     pct_missing = mean(is.na(heart_rate)) * 100
#'   )
"raw_hr"

#' Simulated PROMIS Sleep Assessment Dataset
#'
#' `raw_promis` contains simulated PROMIS Sleep-related questionnaire data
#' collected from two synthetic participants (`P01`, `P02`) at three study
#' stages: **Registration**, **Day‑7**, and **Day‑14**.
#' The dataset is fully synthetic, designed for demonstration, examples, and testing
#' of PROMIS‑related processing workflows in the `hypometrics` package.
#'
#' @details
#'
#' \strong{Participants}
#'
#' \itemize{
#'   \item \code{"P01"} — first assessment at \code{"2026‑01‑01 07:17:00"} UTC
#'   \item \code{"P02"} — first assessment at \code{"2026‑01‑02 15:52:00"} UTC
#' }
#'
#' Follow-up timestamps occur exactly 7 days and 14 days after the Registration
#' timestamp for each participant.
#'
#'
#' \strong{PROMIS Items}
#'
#' The dataset includes 8 PROMIS Sleep items commonly used in PROMIS Sleep Disturbance
#' and PROMIS Sleep-Related Impairment instruments.
#' Each item is a Likert response with values from **1 to 5**:
#'
#' \itemize{
#'   \item \code{Sleep115}
#'   \item \code{Sleep116}
#'   \item \code{Sleep90}
#'   \item \code{Sleep110}
#'   \item \code{Sleep44}
#'   \item \code{Sleep87}
#'   \item \code{Sleep108}
#'   \item \code{Sleep109}
#' }
#'
#' \strong{Generation script}
#'
#' This dataset is created using the reproducible script:
#'
#' \preformatted{
#'   data-raw/simulate_raw_promis.R
#' }
#'
#'
#' @format A tibble with the following columns:
#' \describe{
#'   \item{userid}{Character string identifying the participant (\code{"P01"}, \code{"P02"}).}
#'   \item{stage}{Character variable: one of \code{"Registration"}, \code{"Day-7"}, \code{"Day-14"}.}
#'   \item{localTimestamp}{Character ISO‑8601 timestamp with milliseconds and UTC offset.}
#'   \item{Sleep115}{Integer (1–5) PROMIS item response.}
#'   \item{Sleep116}{Integer (1–5) PROMIS item response.}
#'   \item{Sleep90}{Integer (1–5) PROMIS item response.}
#'   \item{Sleep110}{Integer (1–5) PROMIS item response.}
#'   \item{Sleep44}{Integer (1–5) PROMIS item response.}
#'   \item{Sleep87}{Integer (1–5) PROMIS item response.}
#'   \item{Sleep108}{Integer (1–5) PROMIS item response.}
#'   \item{Sleep109}{Integer (1–5) PROMIS item response.}
#' }
#'
#' @examples
#' data(raw_promis, package = "hypometrics")
#'
#' # View structure
#' dplyr::glimpse(raw_promis)
#'
#' # Filter P01 data
#' raw_promis %>% dplyr::filter(userid == "P01")
#'
#' # PROMIS summary
#' raw_promis %>%
#'   dplyr::group_by(userid, stage) %>%
#'   dplyr::summarise(
#'     across(dplyr::starts_with("Sleep"), mean),
#'     .groups = "drop"
#'   )
"raw_promis"

#' Simulated Daily Check‑In Dataset
#'
#' `raw_checkin` contains fully simulated daily “morning check‑in” questionnaire
#' data for two synthetic participants (`P01`, `P02`) across a 14‑day follow‑up.
#' The dataset includes registration‑day entries followed by daily morning
#' check‑ins through \code{"Day‑14"}.
#'
#' This dataset is **entirely synthetic** and is intended for testing and
#' demonstrating multi‑modal data integration.
#' @details
#'
#' \strong{Generation script}
#'
#' This dataset is produced reproducibly using:
#'
#' \preformatted{
#' data-raw/simulate_raw_checkin.R
#' }
#'
#'
#' @format A tibble with the following character columns:
#' \describe{
#'   \item{userid}{Participant ID (\code{"P01"}, \code{"P02"}).}
#'   \item{stage}{\code{"Registration"} or \code{"Day‑2"}–\code{"Day‑14"}.}
#'   \item{localTimestamp}{Timestamp of check-in questionnaire completion.}
#'   \item{AM_forfirsthypoAtwhattimedidthishappen.}
#'   \item{AM_forfirsthypoHowdidyoudetectyourhypoorahypothatwasabouttohappen.}
#'   \item{AM_forfirsthypoWhathappened.}
#' }
#'
#'
#' @examples
#' data(raw_checkin, package = "hypometrics")
#'
#' # Structure
#' dplyr::glimpse(raw_checkin)
#'
#' # View registration entries
#' raw_checkin %>% dplyr::filter(stage == "Registration")
#'
#' # Rows containing hypo times
#' raw_checkin %>%
#'   dplyr::filter(AM_forfirsthypoAtwhattimedidthishappen != "")
"raw_checkin"


#' Simulated uMotif Segment Dataset
#'
#' `raw_motif_segment` contains a synthetic version of a uMotif-style
#' “Segment” dataset for two simulated participants (`P01`, `P02`).
#' Each participant contributes multiple uMotif timestamps, and for each
#' timestamp, a set of Segment IDs and associated values is recorded.
#'
#' @details
#'
#' \strong{Participants}
#'
#' * \code{"P01"} — uMotif timeline beginning at \code{"2026-01-01 07:17:00"} UTC
#'   with exactly **3 uMotif timestamps** over a 14‑day period.
#'
#' * \code{"P02"} — uMotif timeline beginning at \code{"2026-01-02 15:52:00"} UTC
#'   with exactly **5 uMotif timestamps** over a 14‑day period.
#'
#'
#' \strong{Generation script}
#'
#' The dataset is produced using the reproducible script:
#'
#' \preformatted{
#' data-raw/simulate_raw_motif_segment.R
#' }
#'
#'
#' @format A tibble with the following variables:
#' \describe{
#'   \item{UserId}{Character ID for the participant (\code{"P01"}, \code{"P02"}).}
#'   \item{uMotifTime}{Character timestamp in \code{"YYYY-MM-DD HH:MM:SS"} format.}
#'   \item{SegmentId}{Integer segment code: \code{1–10} for P01, \code{11–20} for P02.}
#'   \item{Value}{Integer value (1–5).}
#' }
#'
#' @examples
#' data(raw_motif_segment, package = "hypometrics")
#'
#' # Inspect structure
#' dplyr::glimpse(raw_motif_segment)
#'
#' # Values for P01 at the hypoglycaemia-aligned timestamp
#' raw_motif_segment %>%
#'   dplyr::filter(UserId == "P01") %>%
#'   dplyr::filter(SegmentId == 1)
#'
#' # Values for P02 at hypoglycaemia-aligned timestamps
#' raw_motif_segment %>%
#'   dplyr::filter(UserId == "P02", SegmentId == 11)
"raw_motif_segment"

#' Simulated PROMIS Sleep Assessment Dataset
#'
#' `raw_promis` contains **synthetic PROMIS Sleep questionnaire data** for two
#' simulated participants across three study stages: \code{"Registration"},
#' \code{"Day-7"}, and \code{"Day-14"}.
#' The dataset includes eight PROMIS Sleep item responses (1–5 Likert scale)
#' alongside participant identifiers and timestamped assessments.
#'
#' This dataset is fully simulated and intended for demonstration, package
#' examples, and testing workflows within `hypometrics`.
#'
#' @details
#'
#' \strong{Participants and timing}
#'
#' \itemize{
#'   \item \code{"P01"} — Registration at \code{"2026-01-01 07:17:00"} UTC
#'   \item \code{"P02"} — Registration at \code{"2026-01-02 15:52:00"} UTC
#' }
#'
#' Follow‑up assessments occur exactly **7** and **14** days after registration.
#
#' \strong{PROMIS Sleep Items (all 1–5 Likert responses)}
#'
#' Each variable corresponds to a validated PROMIS Sleep item:
#'
#' \describe{
#'   \item{Sleep115}{\emph{"I was satisfied with my sleep"}.}
#'   \item{Sleep116}{\emph{"My sleep was refreshing"}.}
#'   \item{Sleep90}{\emph{"I had trouble sleeping"}.}
#'   \item{Sleep110}{\emph{"I got enough sleep"}.}
#'   \item{Sleep44}{\emph{"I had difficulty falling asleep"}.}
#'   \item{Sleep87}{\emph{"I had trouble staying asleep"}.}
#'   \item{Sleep108}{\emph{"My sleep was restless"}.}
#'   \item{Sleep109}{\emph{"My sleep quality was …"}
#'                   (standard PROMIS item stem).}
#' }
#'
#'
#' \strong{Generation script}
#'
#' This dataset is reproducibly generated by:
#'
#' \preformatted{
#' data-raw/simulate_raw_promis.R
#' }
#'
#'
#' @format A tibble with the following variables:
#' \describe{
#'   \item{userid}{Character ID for the participant (\code{"P01"}, \code{"P02"}).}
#'   \item{stage}{Character: \code{"Registration"}, \code{"Day-7"}, \code{"Day-14"}.}
#'   \item{localTimestamp}{Character ISO‑8601 timestamp with milliseconds and UTC offset.}
#'   \item{Sleep115}{Integer 1–5: satisfaction with sleep.}
#'   \item{Sleep116}{Integer 1–5: refreshing quality of sleep.}
#'   \item{Sleep90}{Integer 1–5: trouble sleeping.}
#'   \item{Sleep110}{Integer 1–5: perceived adequacy of sleep.}
#'   \item{Sleep44}{Integer 1–5: difficulty falling asleep.}
#'   \item{Sleep87}{Integer 1–5: trouble staying asleep.}
#'   \item{Sleep108}{Integer 1–5: restless sleep.}
#'   \item{Sleep109}{Integer 1–5: overall sleep quality.}
#' }
#'
#' @examples
#' data(raw_promis, package = "hypometrics")
#'
#' # Inspect structure
#' dplyr::glimpse(raw_promis)
#'
#' # Filter for P01 only
#' raw_promis %>% dplyr::filter(userid == "P01")
#'
#' # Summarise item means by stage
#' raw_promis %>%
#'   dplyr::group_by(userid, stage) %>%
#'   dplyr::summarise(
#'     across(dplyr::starts_with("Sleep"), mean),
#'     .groups = "drop"
#'   )
"raw_promis"

#' Simulated WPAI (Work Productivity and Activity Impairment) Dataset
#'
#' `raw_wpai` contains a fully simulated version of the
#' **WPAI questionnaire**, completed by two synthetic participants
#' (`P01` and `P02`) at three study stages:
#' \code{"Registration"}, \code{"Day-7"}, and \code{"Day-14"}.
#' It includes employment status, work hours missed, hours worked,
#' and perceived hypoglycaemia-related impacts on productivity and
#' daily activities.
#'
#' The dataset is intended for demonstrating how WPAI survey data can be
#' integrated with CGM, HR, step count, and PROMIS data within the
#' `hypometrics` workflow.
#'
#' @details
#'
#' \strong{Participants}
#'
#' \itemize{
#'   \item \code{"P01"} — Registration timestamp: \code{"2026-01-01 07:17:00"} UTC
#'   \item \code{"P02"} — Registration timestamp: \code{"2026-01-02 15:52:00"} UTC
#' }
#'
#' Follow‑up stages occur exactly **7** and **14** days after Registration.
#'
#' \strong{Generation script}
#'
#' This synthetic dataset is produced using:
#'
#' \preformatted{
#' data-raw/simulate_raw_wpai.R
#' }
#'
#' @format A tibble with the following variables:
#' \describe{
#'   \item{userid}{Character: participant ID (\code{"P01"} or \code{"P02"}).}
#'   \item{stage}{Character: one of \code{"Registration"}, \code{"Day-7"}, \code{"Day-14"}.}
#'   \item{localTimestamp}{Character ISO‑8601 timestamp with milliseconds and timezone.}
#'   \item{areyoucurrentlyemployedworkingforpay}{Character (\code{"yes"}, \code{"no"}).}
#'   \item{duringthepastsevendayshowmanyhoursdidyoumissfromworkbecauseofproblemsassociatedwithyourhypoglycaemia}{Numeric 0–3.}
#'   \item{duringthepastsevendayshowmanyhoursdidyoumissfromworkbecauseofanyotherreasonsuchasvacationholidaystimeofftoparticipateinthisstudy}{Numeric 0–50.}
#'   \item{duringthepastsevendayshowmanyhoursdidyouactuallywork}{Numeric 0–70.}
#'   \item{duringthepastsevendayshowmuchdidhypoglycaemiaaffectyourproductivitywhileyouwereworking}{Numeric 1–3.}
#'   \item{duringthepastsevendayshowmuchdidhypoglycaemiaaffectyourabilitytodoyourregulardailyactivitiesotherthanworkatajob}{Numeric 0–3.}
#' }
#'
#' @examples
#' data(raw_wpai, package = "hypometrics")
#'
#' # Explore structure
#' dplyr::glimpse(raw_wpai)
#'
#' # View all stages for P01
#' raw_wpai %>% dplyr::filter(userid == "P01")
#'
#' # Summarise WPAI impacts
#' raw_wpai %>%
#'   dplyr::group_by(userid, stage) %>%
#'   dplyr::summarise(
#'     hrs_missed_hypo = mean(duringthepastsevendayshowmanyhoursdidyoumissfromworkbecauseofproblemsassociatedwithyourhypoglycaemia),
#'     hrs_missed_other = mean(duringthepastsevendayshowmanyhoursdidyoumissfromworkbecauseofanyotherreasonsuchasvacationholidaystimeofftoparticipateinthisstudy),
#'     hrs_worked = mean(duringthepastsevendayshowmanyhoursdidyouactuallywork),
#'     .groups = "drop"
#'   )
"raw_wpai"

#' Simulated EQ‑5D‑5L Health Status Dataset
#'
#' `raw_eq5d5l` contains a fully synthetic version of the EQ‑5D‑5L instrument
#' for two simulated participants (`P01` and `P02`) across three study stages:
#' \code{"Registration"}, \code{"Day-7"}, and \code{"Day-14"}.
#' The dataset includes ISO‑8601 timestamped assessments and categorical responses
#' for each of the five EQ‑5D‑5L dimensions.
#'
#' This dataset is simulated and intended for demonstrating workflows and examples
#' within the `hypometrics` package.
#'
#' @details
#'
#' \strong{Participants and timing}
#'
#' \itemize{
#'   \item \code{"P01"} — Registration time: \code{"2026-01-01 07:17:00"} (UTC)
#'   \item \code{"P02"} — Registration time: \code{"2026-01-02 15:52:00"} (UTC)
#' }
#'
#' Follow‑up assessments occur exactly **7** and **14** days after Registration
#' for each participant.
#'
#' \strong{EQ‑5D‑5L dimensions (each with 5 levels)}
#'
#' Each EQ‑5D‑5L domain is represented using the 5‑level structure, encoded as:
#'
#' \itemize{
#'   \item \code{SC1}–\code{SC5}: **Self‑Care**
#'   \item \code{AD1}–\code{AD5}: **Anxiety/Depression**
#'   \item \code{UA1}–\code{UA5}: **Usual Activities**
#'   \item \code{MB1}–\code{MB5}: **Mobility**
#'   \item \code{PD1}–\code{PD5}: **Pain / Discomfort**
#' }
#'
#'
#' \strong{Generation script}
#'
#' This dataset is produced reproducibly using:
#'
#' \preformatted{
#' data-raw/simulate_raw_eq5d5l.R
#' }
#'
#'
#' @format A tibble with the following variables:
#' \describe{
#'   \item{userid}{Character participant ID (\code{"P01"}, \code{"P02"}).}
#'   \item{stage}{Assessment stage (\code{"Registration"}, \code{"Day-7"}, \code{"Day-14"}).}
#'   \item{localTimestamp}{Character ISO‑8601 timestamp including milliseconds and timezone.}
#'   \item{SC}{Self‑Care domain level (\code{"SC1"}–\code{"SC5"}).}
#'   \item{AD}{Anxiety/Depression domain level (\code{"AD1"}–\code{"AD5"}).}
#'   \item{UA}{Usual Activities domain level (\code{"UA1"}–\code{"UA5"}).}
#'   \item{MB}{Mobility domain level (\code{"MB1"}–\code{"MB5"}).}
#'   \item{PD}{Pain/Discomfort domain level (\code{"PD1"}–\code{"PD5"}).}
#' }
#'
#' @examples
#' data(raw_eq5d5l, package = "hypometrics")
#'
#' # Inspect structure
#' dplyr::glimpse(raw_eq5d5l)
#'
#' # Show values for P01
#' raw_eq5d5l %>% dplyr::filter(userid == "P01")
#'
#' # Summarise EQ-5D-5L domains by participant and stage
#' raw_eq5d5l %>%
#'   dplyr::group_by(userid, stage) %>%
#'   dplyr::summarise(
#'     across(c(SC, AD, UA, MB, PD), ~ dplyr::n_distinct(.x)),
#'     .groups = "drop"
#'   )
"raw_eq5d5l"



